<form>
  <div class="form-group">
    <label for="exampleInputEmail1">Pseudo</label>
    <input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="email">
    <small id="emailHelp" class="form-text text-muted">Merci d'entrer ton pseudo</small>
  </div>
  <div class="form-group">
    <label for="pwd">Mot de passe</label>
    <input type="password" class="form-control" id="pwd" placeholder="Mot de passe">
  </div>
  <button type="submit" class="btn btn-primary">Se connecter</button>
</form>